### ISSUE TITLE
have HtmlTable emit td/thead/tbody elements 

### ISSUE THREAD

**Issue by PerBothner** [zhiburt/tabled#234]
Could I request:
* Group the `<tr>` row elements into `<thead>` and `<tbody>` groups.
* Use `<th>` rather than `<td>` inside the header (`<thead>`).

The latter is easy to do: In `table_to_html/lib.rs` just replace

    tag("td", attrs, text)

by

    tag(if row > 0 {"td"} else {"th"}, attrs, text)

However, do to my limited Rust-fluency I'm having problems with the former - which is actually more important for my needs.

My application: I'm implementing emitting HTML when running nushell under [DomTerm](https://domterm.org).  I basically have this working: the table is displayed as an `<table>` and it looks nice. However, DomTerm has a nice feature when it sees a table with `<thead>` and `<tbody>`: As long as any part of the body is visible, it will show the header at the top of the window: the head stays static while the body scrolls. I think this is quite nice.

**Comment by zhiburt** [comment]
Hi @PerBothner

Thank you for opening the issue.

You totally right that `tbody`, `thead`, `th` must be used.

I think I've addressed it.
Could you try `table_to_html = {  git = "https://github.com/zhiburt/tabled", rev = "4835563ea68260d63a56a4aa18ae77bdb177aaeb" }`

> I'm implementing emitting HTML when running nushell under [DomTerm](https://domterm.org/)

I wonder if you use `table_to_html`?
In which case maybe you have any issues/ideas.
As you may see it's quite basic.

**Comment by PerBothner** [comment]
I'm having some problems. Could you try building nushell with your changes? There might be an incompatible change that nushell doesn't handle:

[error.txt](https://github.com/zhiburt/tabled/files/9795271/error.txt)

The `[[dependencies]]` section of `nushell-mine/crates/nu-table/Cargo.toml` is this:

    [dependencies]
    nu-ansi-term = "0.46.0"
    nu-protocol = { path = "../nu-protocol", version = "0.69.2" }
    strip-ansi-escapes = "0.1.1"
    atty = "0.2.14"
    #tabled = { version = "0.9.0", features = ["color"], default-features = false }
    tabled = { git = "https://github.com/zhiburt/tabled", rev = "4835563ea68260d63a56a4aa18ae77bdb177aaeb", features = ["color"], default-features = false }
    json_to_table = { git = "https://github.com/zhiburt/tabled", rev = "4835563ea68260d63a56a4aa18ae77bdb177aaeb", features =  ["color"] }
    #json_to_table = { version = "0.1.0", features = ["color"] }
    # temporary - assumes 'tabled' directory is a sibling of 'nushell'
    #table_to_html = { path = "../../../tabled/table_to_html", default-features = false }
    table_to_html = { git = "https://github.com/zhiburt/tabled", rev = "4835563ea68260d63a56a4aa18ae77bdb177aaeb" }
    serde_json = "*"

**Comment by PerBothner** [comment]
_"I wonder if you use table_to_html? In which case maybe you have any issues/ideas. As you may see it's quite basic."_

It's a bit early to tell what the issues are.  My inclination is to strip out all styling, and add classes like `nu-record`and `nu-date`. Styling should be done (mostly) using stylesheets. That way styles can be changed dynamically - even for old output.

There needs to be a away to general custom html on a per-cell basis, depending on its type, but I haven't looked into the best way to do that. Custom html should als be generated for non-table values.

**Comment by zhiburt** [comment]
> I'm having some problems. Could you try building nushell with your changes? There might be an incompatible change that nushell doesn't handle:

Use this 

```
table_to_html = { git = "https://github.com/zhiburt/tabled", rev = "970ebc74c437f12ab520a107e617e0428cfea27c" }
json_to_table = { git = "https://github.com/zhiburt/tabled", rev = "970ebc74c437f12ab520a107e617e0428cfea27c", features = ["color"] }
tabled = { git = "https://github.com/zhiburt/tabled", rev = "3d86a327267da9793c5ad9b48c5d6167bc9c9314", features = ["color"] }
```

**Comment by PerBothner** [comment]
I still get:
[err2.txt](https://github.com/zhiburt/tabled/files/9795611/err2.txt)

This is with the following patch:
[nu-diff.txt](https://github.com/zhiburt/tabled/files/9795614/nu-diff.txt)

**Comment by PerBothner** [comment]
It sort-of seems to be working, in the sense I have the table header be fixed at the top of the window while the body scrolls. Yeah!

However, there are some issues I will look at tomorrow.

Also, I assume you'll want to avoid the code duplication in `convert_to_html_table`.

**Comment by PerBothner** [comment]
I fixed the most critical glitches by adding  a `htable.set_border_size(0)` call.
I'll work on making a nushell pull request (as a work-in-progress).

**Comment by PerBothner** [comment]
This NuShell PR makes use of this change:  https://github.com/nushell/nushell/pull/6786 Thanks!

**Comment by PerBothner** [comment]
Thanks!
